version: '3'
services:
  ui:
    container_name: "ui-service"
    image: ui-service
    build: ./ui
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./ui:/code
    depends_on: 
      - api
  api:
    container_name: "api-service"
    image: api-service
    build: ./backend
    ports:
    - "3000:3000"
    volumes:
      - ./backend:/code